steps:

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "sh"
    args: [ '-c', 'docker pull gcr.io/ucdlib-pubreg/rp-ucd-fuseki:latest || true' ]
    env: 
      - 'REPO_NAME=$REPO_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'TAG_NAME=$TAG_NAME'
      - '_UCD_LIB_INITIATOR=$_UCD_LIB_INITIATOR'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "sh"
    args: [ '-c', 'docker build --cache-from gcr.io/ucdlib-pubreg/rp-ucd-fuseki:latest -t gcr.io/ucdlib-pubreg/rp-ucd-fuseki:$TAG_NAME .' ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "sh"
    args: [ '-c', 'docker tag gcr.io/ucdlib-pubreg/rp-ucd-fuseki:$TAG_NAME gcr.io/ucdlib-pubreg/rp-ucd-fuseki:latest' ]

images: ['gcr.io/ucdlib-pubreg/rp-ucd-fuseki:$TAG_NAME', 'gcr.io/ucdlib-pubreg/rp-ucd-fuseki:latest']