#! /bin/bash

# Reads the directories passed on the commmand line, and imports

if ! opts=$(getopt -o g:c:v: --long graph:,clone:,version: -n fuseki-import-graphs -- "$@"); then
  echo "Bad Command Options." >&2 ; exit 1 ; fi

eval set -- "$opts"

local graphs=()
local no_graphs=()

while true; do
	case $1 in
    -c | --clone) clone="$2"; shift 2;;
    -v | --version) version="$2"; shift 2;;
    -p | --private) private=1; shift ;;
    -g | --graph) graphs+=($2); shift 2;;
    -n | --no-graph) no_graphs+=($2); shift 2;;
	  *) shift; break;
  esac
done

auth=admin:${FUSEKI_PASSWORD}

load=http://fuseki:3030/experts/data

if (( ${#graphs[@]} == 0 )); then
  graphs=(
    experts.ucdavis.edu
    experts.ucdavis.edu%2Fiam
    experts.ucdavis.edu%2Foap
    experts.ucdavis.edu%2Ffis
  )
fi

local del
for del in "${no_graph[@]}"
do
   graphs=("${graphs[@]/$del}") #Quotes when working with strings
done

import_dir=/fuseki/import

if [[ -n $clone ]]; then
  [[ -d ${import_dir} ]] || mkdir ${import_dir}
  clone_dir=$(mktemp -d --tmpdir=$import_dir)
  echo "fuseki-import-graphs - git clone $clone $clone_dir"
  git clone $clone $clone_dir;

  # Add to list of diretories
  set -- "$@" $clone_dir
fi

names="${graphs[@]/#/ -o -name }"
names=${names#*-o}

for root in "$@"; do
  for dir in $(find $root -type d $names); do
    for fn in $(find ${dir} -type f -name \*.ttl -o -name \*.ttl.gz ); do
      graph=$(basename $(dirname $fn))
      echo "fuseki-import-graphs - import $graph"
      curl --user "${auth}" -F "file=@$fn" "${load}?graph=$(printf 'http://%b/' ${graph//%/\\x})"
    done
  done
done
